In [43]:
import  numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

In [44]:
X, y = load_iris(return_X_y= True, as_frame= True)
print(X)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


In [45]:
X = X.to_numpy(); y = y.to_numpy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state= 8)
print(X_test)

[[5.  3.6 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [5.2 3.5 1.5 0.2]
 [6.9 3.1 5.1 2.3]
 [6.7 3.1 4.4 1.4]
 [4.9 3.1 1.5 0.2]
 [5.1 3.3 1.7 0.5]
 [6.7 3.  5.2 2.3]
 [6.4 2.8 5.6 2.2]
 [6.4 2.9 4.3 1.3]
 [6.3 3.3 4.7 1.6]
 [4.8 3.1 1.6 0.2]
 [4.9 2.5 4.5 1.7]
 [7.  3.2 4.7 1.4]
 [6.  2.2 5.  1.5]
 [6.3 2.5 5.  1.9]
 [6.4 3.1 5.5 1.8]
 [6.1 3.  4.9 1.8]
 [5.9 3.2 4.8 1.8]
 [7.2 3.  5.8 1.6]
 [6.9 3.1 4.9 1.5]
 [4.9 3.  1.4 0.2]
 [5.8 2.7 4.1 1. ]
 [5.5 2.5 4.  1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 3.5 1.4 0.2]
 [6.9 3.2 5.7 2.3]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [7.7 3.8 6.7 2.2]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.1]
 [4.6 3.6 1.  0.2]
 [6.7 3.3 5.7 2.1]
 [5.5 2.6 4.4 1.2]
 [6.8 2.8 4.8 1.4]
 [6.1 2.6 5.6 1.4]
 [5.6 3.  4.1 1.3]]


In [46]:
class NaiveBayes:

    def __init__(self, X, y):
        self.n_samples, self.n_features = X.shape
        self._classes = np.unique(y)
        self._mean = np.zeros((self.n_samples, self.n_features), dtype= np.float64)
        self._var = np.zeros((self.n_samples, self.n_features), dtype= np.float64)
        self._priors = np.zeros(self.n_samples, dtype= np.float64)
    
    def fit(self):
        
        for index, value in enumerate(self._classes):
            X_c = X[y == value]
            self._mean[index, : ] = X_c.mean(axis= 0)
            self._var[index, : ] = X_c.var(axis= 0)
            self._priors[index] = X_c.shape[0]/self.n_samples

    def predict(self, X_test):
        y_pred = [self._predict(x) for x in X_test]
        return y_pred
    
    def _predict(self, x):
        probaties = []
        
        for i in range(len(self._classes)):
            prior = np.log(self._priors[i])
            probaty = np.sum(np.log(self._pdf(i, x)))
            probaty += prior
            probaties.append(probaty)

        return self._classes[np.argmax(probaties)]
    
    def _pdf(self, index, x):
        mean = self._mean[index]
        var = self._var[index]
        f = (np.exp((-(x - mean)**2) / (2*var))) / np.sqrt(2*np.pi*var)
        return f
        

In [47]:
model = NaiveBayes(X_train, y_train)
model.fit()
y_pred = model.predict(X_test)
for i in range(len(X_test)):
    print("predict:   {}    -->     real:      {}".format(y_pred[i], y_test[i]))
print(accuracy_score(y_pred, y_test))

predict:   0    -->     real:      0
predict:   0    -->     real:      0
predict:   0    -->     real:      0
predict:   2    -->     real:      2
predict:   1    -->     real:      1
predict:   0    -->     real:      0
predict:   0    -->     real:      0
predict:   2    -->     real:      2
predict:   2    -->     real:      2
predict:   1    -->     real:      1
predict:   1    -->     real:      1
predict:   0    -->     real:      0
predict:   1    -->     real:      2
predict:   1    -->     real:      1
predict:   1    -->     real:      2
predict:   2    -->     real:      2
predict:   2    -->     real:      2
predict:   2    -->     real:      2
predict:   2    -->     real:      1
predict:   2    -->     real:      2
predict:   2    -->     real:      1
predict:   0    -->     real:      0
predict:   1    -->     real:      1
predict:   1    -->     real:      1
predict:   1    -->     real:      1
predict:   0    -->     real:      0
predict:   2    -->     real:      2
p